### ISSUE TITLE
Another way adding/removing emoticons

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#138]
without the necessity to edit helpers.php

**Comment by C-Lodder** [comment]
The only way I can think of doing this is to use Joomla's repeatable form fields, however I don't believe the type="media" can be used inside this as it doesn't support 2 modal boxes. So there would have to be 1 media parameter to allow the uploading of images, then a repeatable field where the user can define the path and shortcut. Hopefully there is a more feasible method as I'm not keep on having 2 separate parameters for 1 feature, but none that I can think of currently. It is something that would be nice to have

**Comment by wilsonge** [comment]
I think you'd always need to have 2 fields because you'll always need shortcut and path however it works (whether the field is a custom path or a media form field).

I really want this for v3.1 - that's why I've condensed it into one parameter in the latest version - so it's going to be as simple as doing an array_merge in the future.

**Comment by C-Lodder** [comment]
done
