### ISSUE TITLE
Ability to disable character limit

### ISSUE THREAD

**Issue by C-Lodder** [JoomJunk/shoutbox#159]
This should be done by enter a value of `0` as the character limit

**Comment by wilsonge** [comment]
I think this is a bad idea because you'll find the database truncates the text at a certain point - and the users (and on the majority of sites the super admins) won't have the foggiest idea why. Having said that the mysql text type field should be able to take like 21,844 chars (at a quick google search) so maybe we should just amend the string to state what the maximum value is?

**Comment by C-Lodder** [comment]
@wilsonge - Joomla uses `mediumtext` as the column data type for articles, so we can simply use that.

**Comment by wilsonge** [comment]
It's 3x less than that because we are storing UTF-8 (3 byte) chars and it's actually 16,777,215 bytes.

We could even go with long text if the length of text is really relevant though.

But I'm still not convinced that leaving it to the database limit is a good idea.If people really want to write essays (which is a small minority of users) then they can allow it by setting a huge limit. Adding in a huge number of if statements to disable the text counter and stuff seems super counter-intuitive.

**Comment by C-Lodder** [comment]
It's a shoutbox, to write shouts, not essays. The name says it all, therefore it's used for a specific reason. If users want to write essays, then another extension should be used. We've had a few people asking to remove the character count and no users moaning about not being able to write enough

**Comment by C-Lodder** [comment]
https://github.com/JoomJunk/shoutbox/commit/fe7fd241fcbba7d3d52758d304648ec423130266
