### ISSUE TITLE
betteryouthanme issues #2

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#184]
- [x] move bbcode cursor between tags not behind

- [x] Mass delete
If you want to delete more then 9 (2 digits), the second digit is out of view

- [x] Emoticons
The smileys are stored in [joomla-root]/media/mod_shoutbox/images
but if you check the smileys list (back-end) the path is: [joomla-root]/images/mod_shoutbox/icon_e_biggrin.gif

**Comment by C-Lodder** [comment]
@betteryouthanme - The smilies are now stored in `[joomla-root]/images/mod_shoutbox`. They're no longer in the `media` folder. This change was done so that users can now upload images ;) They get automatically moved when you install/update the shoutbox

**Comment by betteryouthanme** [comment]
In the sceenshot below it looks like i only remove 1 shout but it's 10, the number is not fully displayed
![screenshot_3](https://cloud.githubusercontent.com/assets/8537297/10079394/11a3caf6-62ea-11e5-89ad-802034ec138e.png)

**Comment by C-Lodder** [comment]
Ok yeah I think I saw this on one instance which I will carry on fixing tomorrow. I also noticed in the BBCode screenshot you provided, the smiley isn't showing (only the text version). When you added my changes, did you download it from Github and install properly?

**Comment by betteryouthanme** [comment]
Mass delete: You might set the maximum value to 9, currently it's 10.

The smiley is shown correctly now, i just copied the newer files over the old before..
Maybe you can add a new parameter for the emoticon button? I was thinking to use fa-smile-o by fontawesome (that comes along with my joomla template) or one of my own smilies.

**Comment by C-Lodder** [comment]
With the mass delete, the maximum value allowed will be the total count of shouts in the database.

The emoticon button uses one of the images that is stored in the `images` folder. Well it should be anyway. I do however need to replace this with a smilies that cannot be changed

The reason why you don't see the image is because you haven't installed the update properly. Copying the files is sometimes fine, however with features such as the smilies, the migrations requires either a fresh installation or an update to 6.0.0 (next release).

**Comment by C-Lodder** [comment]
Created a new issue for your first point: https://github.com/JoomJunk/shoutbox/issues/189
